# Generated by Django 3.1 on 2021-03-23 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_store', '0004_auto_20210323_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStorePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('promotional_price', models.FloatField(blank=True, null=True)),
                ('product_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product_store.productstore')),
            ],
            options={
                'verbose_name': 'ProdutoLojaPreço',
                'verbose_name_plural': 'ProdutoLojaPreços',
                'db_table': 'product_store_price',
            },
        ),
    ]
