# Generated by Django 3.1 on 2021-03-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_store_price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstoreprice',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
