# Generated by Django 3.1 on 2021-03-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'ProdutoLoja',
                'verbose_name_plural': 'ProdutosLojas',
                'db_table': 'product_store',
            },
        ),
    ]
