# Generated by Django 3.1 on 2021-03-23 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category'),
        ('store', '0001_initial'),
        ('product_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstore',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product'),
        ),
        migrations.AddField(
            model_name='productstore',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.store'),
        ),
    ]
