# Generated by Django 3.1 on 2021-03-23 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('product_store', '0003_auto_20210323_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstore',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='productstore',
            name='last_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productstore',
            name='last_promotional_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
